"""GENERATED by contracts/codegen/generate.py from ping.schema.yaml - DO NOT EDIT."""

from eunomia_contracts.ping import Ping, validate, validate_full

__all__ = ["Ping", "validate", "validate_full"]
