"""GENERATED by contracts/codegen/generate.py from calibration.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass, field

from eunomia_contracts import _semantics


@dataclass
class Calibration:
    schema: str = ""
    calibration_id: str = ""
    scope: str = ""
    camera_serial: str | None = None
    method: str | None = None
    captured_at: str | None = None
    effective_from: str | None = None
    effective_to: str | None = None
    distortion_coeffs: list = field(default_factory=list)
    intrinsics: dict = field(default_factory=dict)


SCHEMA_ID = "eunomia-calibration/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("calibration_id", "string"),
        ("scope", "string"),
    ],
    warn=[
        ("camera_serial", "string"),
        ("method", "string"),
        ("captured_at", "string"),
        ("effective_from", "string"),
        ("effective_to", "string"),
        ("distortion_coeffs", "array"),
        ("intrinsics", "object"),
    ],
    enums={
        "schema": ["eunomia-calibration/v1"],
        "scope": ["none", "fleet", "per_camera"],
    },
    non_empty=[
        "calibration_id",
    ],
    nullable=[
        "camera_serial",
        "method",
        "captured_at",
        "effective_from",
        "effective_to",
        "intrinsics",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
