"""GENERATED by contracts/codegen/generate.py from capture_stack.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass

from eunomia_contracts import _semantics


@dataclass
class CaptureStack:
    schema: str = ""
    capture_stack_id: str = ""
    version: int = 0
    modality: str = ""
    camera_model: str = ""
    camera_fw: str = ""
    fob_board: str = ""
    fob_fw: str = ""
    gripper_hw: str | None = None
    sd_model: str | None = None
    coordinator_sw: str = ""


SCHEMA_ID = "eunomia-capture-stack/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("capture_stack_id", "string"),
    ],
    warn=[
        ("version", "int"),
        ("modality", "string"),
        ("camera_model", "string"),
        ("camera_fw", "string"),
        ("fob_board", "string"),
        ("fob_fw", "string"),
        ("gripper_hw", "string"),
        ("sd_model", "string"),
        ("coordinator_sw", "string"),
    ],
    enums={
        "modality": ["umi", "teleop"],
        "schema": ["eunomia-capture-stack/v1"],
    },
    non_empty=[
        "capture_stack_id",
    ],
    nullable=[
        "gripper_hw",
        "sd_model",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
