"""GENERATED by contracts/codegen/generate.py from episode.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass

from eunomia_contracts import _semantics


@dataclass
class Episode:
    schema: str = ""
    episode_id: str = ""
    display_id: str = ""
    bimanual_episode_id: str = ""
    episode_ordinal: int = 0
    global_episode_seq: int = 0
    kit_id: str = ""
    side: str = ""
    person_id: str = ""
    task_id: str = ""
    station_id: str = ""
    session_id: str = ""
    calibration_id: str | None = None
    capture_stack_id: str | None = None
    recorded_at: str = ""
    ingested_at: str | None = None
    paired: bool = False
    void: bool = False
    void_reason: str | None = None
    needs_review: bool = False
    archive: int = 0
    recording_suspect: int = 0
    pairing_method: str = ""
    pairing_anomaly: bool = False


SCHEMA_ID = "eunomia-episode/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("episode_id", "string"),
        ("global_episode_seq", "int"),
        ("kit_id", "string"),
        ("side", "string"),
        ("task_id", "string"),
        ("station_id", "string"),
        ("session_id", "string"),
        ("recorded_at", "string"),
    ],
    warn=[
        ("display_id", "string"),
        ("bimanual_episode_id", "string"),
        ("episode_ordinal", "int"),
        ("person_id", "string"),
        ("calibration_id", "string"),
        ("capture_stack_id", "string"),
        ("ingested_at", "string"),
        ("paired", "bool"),
        ("void", "bool"),
        ("void_reason", "string"),
        ("needs_review", "bool"),
        ("archive", "int"),
        ("recording_suspect", "int"),
        ("pairing_method", "string"),
        ("pairing_anomaly", "bool"),
    ],
    enums={
        "pairing_method": ["episode_id", "ordinal_join", "needs_review"],
        "schema": ["eunomia-episode/v1"],
        "side": ["left", "right"],
    },
    non_empty=[
        "episode_id",
        "kit_id",
        "side",
    ],
    nullable=[
        "calibration_id",
        "capture_stack_id",
        "ingested_at",
        "void_reason",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
