"""GENERATED by contracts/codegen/generate.py from footage_reference.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass, field

from eunomia_contracts import _semantics


@dataclass
class FootageReference:
    schema: str = ""
    episode_id: str = ""
    footage_state: str = ""
    locations: list = field(default_factory=list)
    hash: str | None = None
    spot_check_selected: bool = False
    selection_method: str = ""
    rendered_on_hades_at: str | None = None
    purge_eligible_at: str | None = None


SCHEMA_ID = "eunomia-footage-reference/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("episode_id", "string"),
        ("footage_state", "string"),
    ],
    warn=[
        ("locations", "array"),
        ("hash", "string"),
        ("spot_check_selected", "bool"),
        ("selection_method", "string"),
        ("rendered_on_hades_at", "string"),
        ("purge_eligible_at", "string"),
    ],
    enums={
        "footage_state": ["on_card", "on_styx", "shipped", "on_hades", "purged"],
        "schema": ["eunomia-footage-reference/v1"],
        "selection_method": ["qc_sample", "manual_pull"],
    },
    non_empty=[
        "episode_id",
    ],
    nullable=[
        "hash",
        "rendered_on_hades_at",
        "purge_eligible_at",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
