"""GENERATED by contracts/codegen/generate.py from hardware_unit.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass, field

from eunomia_contracts import _semantics


@dataclass
class Provisioning:
    wifi_ssid: str = ""
    wifi_ap: str = ""
    ip_scheme: str = ""
    firmware_version: str = ""


@dataclass
class HardwareUnit:
    schema: str = ""
    unit_id: str = ""
    type: str = ""
    body_serial: str | None = None
    insv_serial: str | None = None
    mac: str | None = None
    batch_id: str | None = None
    order_id: str | None = None
    hardware_version: str | None = None
    status: str = ""
    kit_id: str | None = None
    side: str = ""
    camera_id: str | None = None
    fob_id: str | None = None
    board: str | None = None
    mount: str | None = None
    provisioning: Provisioning = field(default_factory=Provisioning)


SCHEMA_ID = "eunomia-hardware-unit/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("unit_id", "string"),
        ("type", "string"),
    ],
    warn=[
        ("body_serial", "string"),
        ("insv_serial", "string"),
        ("mac", "string"),
        ("batch_id", "string"),
        ("order_id", "string"),
        ("hardware_version", "string"),
        ("status", "string"),
        ("kit_id", "string"),
        ("side", "string"),
        ("camera_id", "string"),
        ("fob_id", "string"),
        ("board", "string"),
        ("mount", "string"),
        ("provisioning", "object"),
        ("provisioning.wifi_ssid", "string"),
        ("provisioning.wifi_ap", "string"),
        ("provisioning.ip_scheme", "string"),
        ("provisioning.firmware_version", "string"),
    ],
    enums={
        "schema": ["eunomia-hardware-unit/v1"],
        "side": ["left", "right"],
    },
    non_empty=[
        "unit_id",
        "type",
    ],
    nullable=[
        "body_serial",
        "insv_serial",
        "mac",
        "batch_id",
        "order_id",
        "hardware_version",
        "kit_id",
        "camera_id",
        "fob_id",
        "board",
        "mount",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
