"""GENERATED by contracts/codegen/generate.py from kit.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass

from eunomia_contracts import _semantics


@dataclass
class Kit:
    schema: str = ""
    kit_id: str = ""
    left_cam_unit_id: str | None = None
    right_cam_unit_id: str | None = None
    fob_unit_id: str | None = None
    effective_from: str | None = None
    effective_to: str | None = None


SCHEMA_ID = "eunomia-kit/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("kit_id", "string"),
    ],
    warn=[
        ("left_cam_unit_id", "string"),
        ("right_cam_unit_id", "string"),
        ("fob_unit_id", "string"),
        ("effective_from", "string"),
        ("effective_to", "string"),
    ],
    enums={
        "schema": ["eunomia-kit/v1"],
    },
    non_empty=[
        "kit_id",
    ],
    nullable=[
        "left_cam_unit_id",
        "right_cam_unit_id",
        "fob_unit_id",
        "effective_from",
        "effective_to",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
