"""GENERATED by contracts/codegen/generate.py from operational_event.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass, field

from eunomia_contracts import _semantics


@dataclass
class OperationalEvent:
    schema: str = ""
    event_id: str = ""
    event_type: str = ""
    entity: str = ""
    entity_id: str = ""
    as_of: str | None = None
    reason: str | None = None
    related_unit_id: str | None = None
    related_kit_id: str | None = None
    payload: dict = field(default_factory=dict)


SCHEMA_ID = "eunomia-operational-event/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("event_id", "string"),
        ("event_type", "string"),
        ("entity", "string"),
        ("entity_id", "string"),
    ],
    warn=[
        ("as_of", "string"),
        ("reason", "string"),
        ("related_unit_id", "string"),
        ("related_kit_id", "string"),
        ("payload", "object"),
    ],
    enums={
        "schema": ["eunomia-operational-event/v1"],
    },
    non_empty=[
        "event_id",
        "event_type",
        "entity",
        "entity_id",
    ],
    nullable=[
        "as_of",
        "reason",
        "related_unit_id",
        "related_kit_id",
        "payload",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
