"""GENERATED by contracts/codegen/generate.py from person.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass, field

from eunomia_contracts import _semantics


@dataclass
class Person:
    schema: str = ""
    person_id: str = ""
    name: str | None = None
    role: str = ""
    status: str = ""
    onboarded_at: str | None = None
    offboarded_at: str | None = None
    site_ids: list = field(default_factory=list)


SCHEMA_ID = "eunomia-person/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("person_id", "string"),
    ],
    warn=[
        ("name", "string"),
        ("role", "string"),
        ("status", "string"),
        ("onboarded_at", "string"),
        ("offboarded_at", "string"),
        ("site_ids", "array"),
    ],
    enums={
        "schema": ["eunomia-person/v1"],
    },
    non_empty=[
        "person_id",
    ],
    nullable=[
        "name",
        "onboarded_at",
        "offboarded_at",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
