"""GENERATED by contracts/codegen/generate.py from release.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass, field

from eunomia_contracts import _semantics


@dataclass
class Release:
    schema: str = ""
    episode_id: str = ""
    display_id: str = ""
    bimanual_episode_id: str = ""
    episode_ordinal: int = 0
    global_episode_seq: int = 0
    kit_id: str = ""
    side: str = ""
    camera_id: str = ""
    body_serial: str | None = None
    insv_serial: str | None = None
    person_id: str = ""
    person_name: str | None = None
    station_id: str = ""
    task_id: str = ""
    task_name: str = ""
    prompt: str = ""
    rotation_id: str = ""
    session_id: str = ""
    recorded_at: str = ""
    camera_clock: str | None = None
    ingested_at: str = ""
    time_confidence: str = ""
    capture_stack_id: str | None = None
    modality: str = ""
    camera_firmware: str = ""
    fob_id: str = ""
    fob_build: str = ""
    kit_version: str = ""
    record_format_version: int = 0
    record_settings: str = ""
    site_id: str = ""
    calibration_id: str | None = None
    qc_flags: list = field(default_factory=list)
    qc_reasons: list = field(default_factory=list)
    qc_score: float | None = None
    probe_failed: bool = False
    decode_skipped: bool = False
    sync_offset_ms: float | None = None
    sync_confidence: float | None = None
    paired: bool = False
    void: bool = False
    void_reason: str | None = None
    needs_review: bool = False
    archive: int = 0
    recording_suspect: int = 0
    label_source: str = ""
    pairing_method: str = ""
    pairing_anomaly: bool = False
    human_label: str | None = None
    task_completed: bool | None = None


SCHEMA_ID = "eunomia-release/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("episode_id", "string"),
        ("global_episode_seq", "int"),
        ("kit_id", "string"),
        ("side", "string"),
        ("station_id", "string"),
        ("task_id", "string"),
        ("session_id", "string"),
        ("recorded_at", "string"),
        ("ingested_at", "string"),
        ("time_confidence", "string"),
    ],
    warn=[
        ("display_id", "string"),
        ("bimanual_episode_id", "string"),
        ("episode_ordinal", "int"),
        ("camera_id", "string"),
        ("body_serial", "string"),
        ("insv_serial", "string"),
        ("person_id", "string"),
        ("person_name", "string"),
        ("task_name", "string"),
        ("prompt", "string"),
        ("rotation_id", "string"),
        ("camera_clock", "string"),
        ("capture_stack_id", "string"),
        ("modality", "string"),
        ("camera_firmware", "string"),
        ("fob_id", "string"),
        ("fob_build", "string"),
        ("kit_version", "string"),
        ("record_format_version", "int"),
        ("record_settings", "string"),
        ("site_id", "string"),
        ("calibration_id", "string"),
        ("qc_flags", "array"),
        ("qc_reasons", "array"),
        ("qc_score", "number"),
        ("probe_failed", "bool"),
        ("decode_skipped", "bool"),
        ("sync_offset_ms", "number"),
        ("sync_confidence", "number"),
        ("paired", "bool"),
        ("void", "bool"),
        ("void_reason", "string"),
        ("needs_review", "bool"),
        ("archive", "int"),
        ("recording_suspect", "int"),
        ("label_source", "string"),
        ("pairing_method", "string"),
        ("pairing_anomaly", "bool"),
        ("human_label", "string"),
        ("task_completed", "bool"),
    ],
    enums={
        "modality": ["umi", "teleop"],
        "pairing_method": ["episode_id", "ordinal_join", "needs_review"],
        "schema": ["eunomia-release/v1"],
        "side": ["left", "right"],
        "time_confidence": ["ntp_synced", "unsynced_monotonic"],
    },
    non_empty=[
        "kit_id",
        "side",
    ],
    nullable=[
        "body_serial",
        "insv_serial",
        "person_name",
        "camera_clock",
        "capture_stack_id",
        "calibration_id",
        "qc_score",
        "sync_offset_ms",
        "sync_confidence",
        "void_reason",
        "human_label",
        "task_completed",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
