"""GENERATED by contracts/codegen/generate.py from session.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass

from eunomia_contracts import _semantics


@dataclass
class Session:
    schema: str = ""
    session_id: str = ""
    person_id: str = ""
    kit_id: str = ""
    site_id: str = ""
    station_id: str = ""
    fob_session_id: str = ""
    signed_in_at: str | None = None
    signed_out_at: str | None = None
    task_id: str | None = None
    pause_count: int = 0
    total_pause_ms: float = 0.0


SCHEMA_ID = "eunomia-session/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("session_id", "string"),
    ],
    warn=[
        ("person_id", "string"),
        ("kit_id", "string"),
        ("site_id", "string"),
        ("station_id", "string"),
        ("fob_session_id", "string"),
        ("signed_in_at", "string"),
        ("signed_out_at", "string"),
        ("task_id", "string"),
        ("pause_count", "int"),
        ("total_pause_ms", "number"),
    ],
    enums={
        "schema": ["eunomia-session/v1"],
    },
    non_empty=[
        "session_id",
    ],
    nullable=[
        "signed_in_at",
        "signed_out_at",
        "task_id",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
