"""GENERATED by contracts/codegen/generate.py from sidecar.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass, field

from eunomia_contracts import _semantics


@dataclass
class Identity:
    camera_id: str = ""
    kit_id: str = ""
    side: str = ""
    operator_id: str = ""
    station_id: str = ""
    task_id: str = ""
    task_name: str = ""
    session_id: str = ""
    episode_id: str = ""
    rotation_id: str = ""
    prompt: str = ""
    task_source: str = ""
    episode_ordinal: int = 0
    bimanual_episode_id: str = ""
    display_id: str = ""
    calibration_id: str | None = None
    record_settings: str = ""
    mount: str = ""
    assignment_source: str = ""
    setup_version_id: str | None = None


@dataclass
class Timing:
    started_unix: float = 0.0
    stopped_unix: float = 0.0
    start_skew_ms: float = 0.0
    camera_clock: str | None = None


@dataclass
class Provenance:
    camera_firmware: str = ""
    fob_id: str = ""
    fob_build: str = ""
    kit_version: str = ""
    site_id: str = ""
    modality: str = ""


@dataclass
class Outcome:
    stop_reason: str = ""
    archive: int = 0
    recording_suspect: int = 0


@dataclass
class Files:
    back: str = ""


@dataclass
class Sidecar:
    schema: str = ""
    record_format_version: int = 0
    seq: int = 0
    global_episode_seq: int = 0
    identity: Identity = field(default_factory=Identity)
    timing: Timing = field(default_factory=Timing)
    provenance: Provenance = field(default_factory=Provenance)
    outcome: Outcome = field(default_factory=Outcome)
    files: Files = field(default_factory=Files)


SCHEMA_ID = "eunomia-sidecar/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("seq", "int"),
        ("global_episode_seq", "int"),
        ("identity", "object"),
        ("identity.camera_id", "string"),
        ("identity.kit_id", "string"),
        ("identity.side", "string"),
        ("identity.operator_id", "string"),
        ("identity.station_id", "string"),
        ("identity.task_id", "string"),
        ("identity.task_name", "string"),
        ("identity.session_id", "string"),
        ("identity.episode_id", "string"),
        ("identity.rotation_id", "string"),
        ("files", "object"),
        ("files.back", "string"),
    ],
    warn=[
        ("record_format_version", "int"),
        ("identity.episode_ordinal", "int"),
        ("identity.bimanual_episode_id", "string"),
        ("identity.display_id", "string"),
        ("identity.calibration_id", "string"),
        ("identity.record_settings", "string"),
        ("identity.mount", "string"),
        ("identity.assignment_source", "string"),
        ("identity.setup_version_id", "string"),
        ("timing", "object"),
        ("timing.started_unix", "number"),
        ("timing.stopped_unix", "number"),
        ("timing.start_skew_ms", "number"),
        ("timing.camera_clock", "string"),
        ("provenance", "object"),
        ("provenance.camera_firmware", "string"),
        ("provenance.fob_id", "string"),
        ("provenance.fob_build", "string"),
        ("provenance.kit_version", "string"),
        ("provenance.site_id", "string"),
        ("provenance.modality", "string"),
        ("outcome", "object"),
        ("outcome.stop_reason", "string"),
        ("outcome.archive", "int"),
        ("outcome.recording_suspect", "int"),
    ],
    enums={
        "identity.side": ["left", "right"],
        "identity.task_source": ["nand_staged", "sd_assignment", "none"],
        "outcome.stop_reason": [
            "operator",
            "timer",
            "card_full",
            "battery",
            "error",
            "overheat",
        ],
        "provenance.modality": ["umi", "teleop"],
        "schema": ["eunomia-sidecar/v1"],
    },
    non_empty=[
        "identity.kit_id",
        "identity.side",
    ],
    nullable=[
        "identity.calibration_id",
        "identity.setup_version_id",
        "timing.camera_clock",
    ],
    cond_pattern="^eunomia-sidecar/v[1-9][0-9]*$",
    cond_fields=[
        ("identity.prompt", "string"),
        ("identity.task_source", "string"),
    ],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
