"""GENERATED by contracts/codegen/generate.py from station.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass

from eunomia_contracts import _semantics


@dataclass
class Station:
    schema: str = ""
    station_id: str = ""
    site_id: str = ""
    status: str = ""
    label: str | None = None
    registered_at: str | None = None
    retired_at: str | None = None


SCHEMA_ID = "eunomia-station/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("station_id", "string"),
        ("site_id", "string"),
    ],
    warn=[
        ("status", "string"),
        ("label", "string"),
        ("registered_at", "string"),
        ("retired_at", "string"),
    ],
    enums={
        "schema": ["eunomia-station/v1"],
    },
    non_empty=[
        "station_id",
        "site_id",
    ],
    nullable=[
        "label",
        "registered_at",
        "retired_at",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
