"""GENERATED by contracts/codegen/generate.py from sync_delta.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass, field

from eunomia_contracts import _semantics


@dataclass
class SyncDelta:
    schema: str = ""
    delta_seq: int = 0
    emitted_at: str = ""
    entity: str = ""
    op: str = ""
    entity_id: str = ""
    as_of: str | None = None
    payload: dict = field(default_factory=dict)


SCHEMA_ID = "eunomia-sync-delta/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("delta_seq", "int"),
        ("emitted_at", "string"),
        ("entity", "string"),
        ("op", "string"),
        ("entity_id", "string"),
    ],
    warn=[
        ("as_of", "string"),
        ("payload", "object"),
    ],
    enums={
        "op": ["upsert", "delete"],
        "schema": ["eunomia-sync-delta/v1"],
    },
    non_empty=[
        "entity",
        "entity_id",
    ],
    nullable=[
        "as_of",
        "payload",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
