"""GENERATED by contracts/codegen/generate.py from task_station_assignment.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass

from eunomia_contracts import _semantics


@dataclass
class TaskStationAssignment:
    schema: str = ""
    assignment_id: str = ""
    site_id: str = ""
    station_id: str = ""
    task_id: str = ""
    task_version: int | None = None
    rotation_id: str | None = None
    effective_from: str = ""
    effective_to: str | None = None
    assigned_by: str | None = None
    created_at: str | None = None


SCHEMA_ID = "eunomia-task-station-assignment/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("assignment_id", "string"),
        ("site_id", "string"),
        ("station_id", "string"),
        ("task_id", "string"),
        ("effective_from", "string"),
    ],
    warn=[
        ("task_version", "int"),
        ("rotation_id", "string"),
        ("effective_to", "string"),
        ("assigned_by", "string"),
        ("created_at", "string"),
    ],
    enums={
        "schema": ["eunomia-task-station-assignment/v1"],
    },
    non_empty=[
        "assignment_id",
        "site_id",
        "station_id",
        "task_id",
    ],
    nullable=[
        "task_version",
        "rotation_id",
        "effective_to",
        "assigned_by",
        "created_at",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
