"""GENERATED by contracts/codegen/generate.py from task.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass

from eunomia_contracts import _semantics


@dataclass
class Task:
    schema: str = ""
    task_id: str = ""
    version: int = 0
    task_name: str = ""
    prompt: str = ""
    rotation_id: str = ""
    station_id: str = ""
    category: str | None = None
    family: str | None = None
    bimanual: bool = False
    expected_duration_s: float | None = None
    effective_from: str | None = None
    effective_to: str | None = None


SCHEMA_ID = "eunomia-task/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("task_id", "string"),
    ],
    warn=[
        ("version", "int"),
        ("task_name", "string"),
        ("prompt", "string"),
        ("rotation_id", "string"),
        ("station_id", "string"),
        ("category", "string"),
        ("family", "string"),
        ("bimanual", "bool"),
        ("expected_duration_s", "number"),
        ("effective_from", "string"),
        ("effective_to", "string"),
    ],
    enums={
        "schema": ["eunomia-task/v1"],
    },
    non_empty=[
        "task_id",
    ],
    nullable=[
        "category",
        "family",
        "expected_duration_s",
        "effective_from",
        "effective_to",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
