"""GENERATED by contracts/codegen/generate.py from telemetry_event.schema.yaml - DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass, field

from eunomia_contracts import _semantics


@dataclass
class TelemetryEvent:
    schema: str = ""
    event: str = ""
    kit_id: str = ""
    ms: int = 0
    emitted_at: str = ""
    fob_session_id: str = ""
    episode_id: str | None = None
    episode_ordinal: int = 0
    side: str = ""
    station: str = ""
    prompt: str = ""
    cams: list = field(default_factory=list)
    sent: int = 0
    total: int = 0


SCHEMA_ID = "eunomia-telemetry-event/v1"

_TABLES = _semantics.Tables(
    hard=[
        ("schema", "string"),
        ("event", "string"),
        ("kit_id", "string"),
        ("ms", "int"),
        ("emitted_at", "string"),
    ],
    warn=[
        ("fob_session_id", "string"),
        ("episode_id", "string"),
        ("episode_ordinal", "int"),
        ("side", "string"),
        ("station", "string"),
        ("prompt", "string"),
        ("cams", "array"),
        ("sent", "int"),
        ("total", "int"),
    ],
    enums={
        "event": ["started", "stopped", "camera_dropped", "recording_suspect"],
        "schema": ["eunomia-telemetry-event/v1"],
        "side": ["left", "right"],
    },
    non_empty=[
        "kit_id",
    ],
    nullable=[
        "episode_id",
    ],
    cond_pattern="",
    cond_fields=[],
)


def validate(obj: dict) -> list[str]:
    """Return HARD errors only (empty == safe to ingest, CONTRACT §6)."""
    return _semantics.validate(obj, _TABLES, SCHEMA_ID)


def validate_full(obj: dict) -> tuple[list[str], list[str]]:
    """Return (hard_errors, warnings)."""
    return _semantics.validate_full(obj, _TABLES, SCHEMA_ID)
