// GENERATED by contracts/codegen/generate_interfaces.py from interfaces/ports.iface.yaml - DO NOT EDIT (edit the source + run `make codegen`).
#ifndef EUNOMIA_COORDINATOR_PORT_H
#define EUNOMIA_COORDINATOR_PORT_H

#include <string>
#include <vector>

#include "eunomia_sidecar.h"

// Generated ABSTRACT INTERFACE (Run 0c, LEAD-OQ-A option C): a pure-virtual C++ port emitted from
// contracts/interfaces/ports.iface.yaml by contracts/codegen/generate_interfaces.py (a SEPARATE
// mini-emitter, NOT the record generator). Firmware implements this port; a board/camera swap is a
// new implementation of the same port, nothing upstream changes. This is NOT a data record — there
// is no JSON Schema target. Kept in sync with the Python Protocol (eunomia_contracts.interfaces) by
// the single codegen-drift gate: one source -> two targets, so they cannot drift.

namespace eunomia {

// The fob/coordinator seam (CONTRACT §1.6 "Contract A"). Whatever the coordinator IS (an ESP32 today, a phone/other MCU tomorrow), it implements these. Recording depends on the on-camera agent holding video mode, so the coordinator does NOT arm per take.
class CoordinatorPort {
 public:
  virtual ~CoordinatorPort() = default;

  // Mint a globally-unique UUIDv4 episode_id at START, written identically to both arms (the pairing key, §7).
  virtual std::string mint_episode_id() = 0;

  // Trigger the given capture devices near-simultaneously, serialized under one client (§1.7). The phantom-press gate: a START only advances when both cams acked (sent==2). Returns the ack.
  virtual bool trigger(const std::vector<std::string>& cameras) = 0;

  // Read back the clip filename for a camera (recovered at STOP via the device, never the OSC response — §1.7).
  virtual std::string read_clip_filename(const std::string& camera) = 0;

  // Write the sidecar record onto a camera's capture medium (the label rides on the card, §1.2/§2).
  virtual void write_sidecar(const std::string& camera, const eunomia::Sidecar& record) = 0;

  // Return the set of dropped capture devices, detected at the L2/network-association layer (never by OSC polling, §1.3).
  virtual std::vector<std::string> detect_drop() = 0;

  // Flush queued god's-view telemetry events in the idle gap (single-radio constraint, §1.4).
  virtual void flush_telemetry() = 0;
};

}  // namespace eunomia

#endif  // EUNOMIA_COORDINATOR_PORT_H
