// GENERATED by contracts/codegen/generate.py from sidecar.schema.yaml - DO NOT EDIT.
#ifndef EUNOMIA_SIDECAR_H
#define EUNOMIA_SIDECAR_H

#include <string>

#include "eunomia_detail.h"

// Firmware-facing C++ target (OQ-5): a flat field-BAG view of the record. The struct flattens every
// scalar/string leaf (nested groups are flattened by their unique leaf key); parse/serialize look
// leaves up by key in the whole JSON (NO structural descent, via eunomia_detail.h). HARD leaves are
// required by parse(); WARN leaves are best-effort. Arrays / opaque objects / bool are not modeled.

namespace eunomia {

struct Sidecar {
  std::string schema{};
  long long record_format_version{};
  long long seq{};
  long long global_episode_seq{};
  std::string camera_id{};
  std::string kit_id{};
  std::string side{};
  std::string operator_id{};
  std::string station_id{};
  std::string task_id{};
  std::string task_name{};
  std::string session_id{};
  std::string episode_id{};
  std::string rotation_id{};
  std::string prompt{};
  std::string task_source{};
  long long episode_ordinal{};
  std::string bimanual_episode_id{};
  std::string display_id{};
  std::string calibration_id{};
  std::string record_settings{};
  std::string mount{};
  std::string assignment_source{};
  std::string setup_version_id{};
  double started_unix{};
  double stopped_unix{};
  double start_skew_ms{};
  std::string camera_clock{};
  std::string camera_firmware{};
  std::string fob_id{};
  std::string fob_build{};
  std::string kit_version{};
  std::string site_id{};
  std::string modality{};
  std::string stop_reason{};
  long long archive{};
  long long recording_suspect{};
  std::string back{};
};

inline bool parse_sidecar(const std::string& s, Sidecar& out) {
  if (!parse_string(s, "schema", out.schema)) return false;
  parse_number(s, "record_format_version", out.record_format_version);
  if (!parse_number(s, "seq", out.seq)) return false;
  if (!parse_number(s, "global_episode_seq", out.global_episode_seq)) return false;
  if (!parse_string(s, "camera_id", out.camera_id)) return false;
  if (!parse_string(s, "kit_id", out.kit_id)) return false;
  if (!parse_string(s, "side", out.side)) return false;
  if (!parse_string(s, "operator_id", out.operator_id)) return false;
  if (!parse_string(s, "station_id", out.station_id)) return false;
  if (!parse_string(s, "task_id", out.task_id)) return false;
  if (!parse_string(s, "task_name", out.task_name)) return false;
  if (!parse_string(s, "session_id", out.session_id)) return false;
  if (!parse_string(s, "episode_id", out.episode_id)) return false;
  if (!parse_string(s, "rotation_id", out.rotation_id)) return false;
  if (!parse_string(s, "prompt", out.prompt)) return false;
  if (!parse_string(s, "task_source", out.task_source)) return false;
  parse_number(s, "episode_ordinal", out.episode_ordinal);
  parse_string(s, "bimanual_episode_id", out.bimanual_episode_id);
  parse_string(s, "display_id", out.display_id);
  parse_string(s, "calibration_id", out.calibration_id);
  parse_string(s, "record_settings", out.record_settings);
  parse_string(s, "mount", out.mount);
  parse_string(s, "assignment_source", out.assignment_source);
  parse_string(s, "setup_version_id", out.setup_version_id);
  parse_number(s, "started_unix", out.started_unix);
  parse_number(s, "stopped_unix", out.stopped_unix);
  parse_number(s, "start_skew_ms", out.start_skew_ms);
  parse_string(s, "camera_clock", out.camera_clock);
  parse_string(s, "camera_firmware", out.camera_firmware);
  parse_string(s, "fob_id", out.fob_id);
  parse_string(s, "fob_build", out.fob_build);
  parse_string(s, "kit_version", out.kit_version);
  parse_string(s, "site_id", out.site_id);
  parse_string(s, "modality", out.modality);
  parse_string(s, "stop_reason", out.stop_reason);
  parse_number(s, "archive", out.archive);
  parse_number(s, "recording_suspect", out.recording_suspect);
  if (!parse_string(s, "back", out.back)) return false;
  return true;
}

inline std::string serialize_sidecar(const Sidecar& v) {
  std::string o = "{";
  o += "\"schema\":\"" + v.schema + "\"";
  o += ",\"record_format_version\":" + std::to_string(v.record_format_version);
  o += ",\"seq\":" + std::to_string(v.seq);
  o += ",\"global_episode_seq\":" + std::to_string(v.global_episode_seq);
  o += ",\"camera_id\":\"" + v.camera_id + "\"";
  o += ",\"kit_id\":\"" + v.kit_id + "\"";
  o += ",\"side\":\"" + v.side + "\"";
  o += ",\"operator_id\":\"" + v.operator_id + "\"";
  o += ",\"station_id\":\"" + v.station_id + "\"";
  o += ",\"task_id\":\"" + v.task_id + "\"";
  o += ",\"task_name\":\"" + v.task_name + "\"";
  o += ",\"session_id\":\"" + v.session_id + "\"";
  o += ",\"episode_id\":\"" + v.episode_id + "\"";
  o += ",\"rotation_id\":\"" + v.rotation_id + "\"";
  o += ",\"prompt\":\"" + v.prompt + "\"";
  o += ",\"task_source\":\"" + v.task_source + "\"";
  o += ",\"episode_ordinal\":" + std::to_string(v.episode_ordinal);
  o += ",\"bimanual_episode_id\":\"" + v.bimanual_episode_id + "\"";
  o += ",\"display_id\":\"" + v.display_id + "\"";
  o += ",\"calibration_id\":\"" + v.calibration_id + "\"";
  o += ",\"record_settings\":\"" + v.record_settings + "\"";
  o += ",\"mount\":\"" + v.mount + "\"";
  o += ",\"assignment_source\":\"" + v.assignment_source + "\"";
  o += ",\"setup_version_id\":\"" + v.setup_version_id + "\"";
  o += ",\"started_unix\":" + std::to_string(v.started_unix);
  o += ",\"stopped_unix\":" + std::to_string(v.stopped_unix);
  o += ",\"start_skew_ms\":" + std::to_string(v.start_skew_ms);
  o += ",\"camera_clock\":\"" + v.camera_clock + "\"";
  o += ",\"camera_firmware\":\"" + v.camera_firmware + "\"";
  o += ",\"fob_id\":\"" + v.fob_id + "\"";
  o += ",\"fob_build\":\"" + v.fob_build + "\"";
  o += ",\"kit_version\":\"" + v.kit_version + "\"";
  o += ",\"site_id\":\"" + v.site_id + "\"";
  o += ",\"modality\":\"" + v.modality + "\"";
  o += ",\"stop_reason\":\"" + v.stop_reason + "\"";
  o += ",\"archive\":" + std::to_string(v.archive);
  o += ",\"recording_suspect\":" + std::to_string(v.recording_suspect);
  o += ",\"back\":\"" + v.back + "\"";
  o += "}";
  return o;
}

}  // namespace eunomia

#endif  // EUNOMIA_SIDECAR_H
