// GENERATED by contracts/codegen/generate.py from ping.schema.yaml - DO NOT EDIT.
#ifndef EUNOMIA_PING_H
#define EUNOMIA_PING_H

#include <cstddef>
#include <cstdlib>
#include <string>

namespace eunomia {

struct Ping {
  long long seq{};
  double sent_unix{};
};

namespace detail {
inline bool find_value(const std::string& s, const std::string& key, std::size_t& pos) {
  std::string needle = "\"" + key + "\"";
  std::size_t k = s.find(needle);
  if (k == std::string::npos) return false;
  std::size_t c = s.find(':', k + needle.size());
  if (c == std::string::npos) return false;
  std::size_t p = c + 1;
  while (p < s.size() && (s[p] == ' ' || s[p] == '\t' || s[p] == '\n' || s[p] == '\r')) p++;
  if (p >= s.size()) return false;
  pos = p;
  return true;
}
}  // namespace detail

template <typename T>
inline bool parse_number(const std::string& s, const std::string& key, T& out) {
  std::size_t p = 0;
  if (!detail::find_value(s, key, p)) return false;
  char c = s[p];
  if (!(c == '-' || c == '+' || c == '.' || (c >= '0' && c <= '9'))) return false;
  out = static_cast<T>(std::strtod(s.c_str() + p, nullptr));
  return true;
}

inline bool parse_ping(const std::string& s, Ping& out) {
  if (!parse_number(s, "seq", out.seq)) return false;
  if (!parse_number(s, "sent_unix", out.sent_unix)) return false;
  return true;
}

inline std::string serialize_ping(const Ping& v) {
  std::string o = "{";
  o += "\"seq\":" + std::to_string(v.seq);
  o += ",\"sent_unix\":" + std::to_string(v.sent_unix);
  o += "}";
  return o;
}

}  // namespace eunomia

#endif  // EUNOMIA_PING_H
