// GENERATED by contracts/codegen/generate_interfaces.py from interfaces/ports.iface.yaml - DO NOT EDIT (edit the source + run `make codegen`).
#ifndef EUNOMIA_CAPTURE_DEVICE_PORT_H
#define EUNOMIA_CAPTURE_DEVICE_PORT_H

#include <string>

#include "eunomia_sidecar.h"

// Generated ABSTRACT INTERFACE (Run 0c, LEAD-OQ-A option C): a pure-virtual C++ port emitted from
// contracts/interfaces/ports.iface.yaml by contracts/codegen/generate_interfaces.py (a SEPARATE
// mini-emitter, NOT the record generator). Firmware implements this port; a board/camera swap is a
// new implementation of the same port, nothing upstream changes. This is NOT a data record — there
// is no JSON Schema target. Kept in sync with the Python Protocol (eunomia_contracts.interfaces) by
// the single codegen-drift gate: one source -> two targets, so they cannot drift.

namespace eunomia {

// The camera seam (CONTRACT §1.6 "Contract B"). Whatever the camera IS, the coordinator drives it through an adapter exposing these six operations. Today: OSC + a telnet shell against the X3's hidcap firmware. A different camera = a different adapter implementing the same port.
class CaptureDevicePort {
 public:
  virtual ~CaptureDevicePort() = default;

  // Start capture (directly — no per-take arm; the device is held in video mode, §1.7).
  virtual void start() = 0;

  // Stop capture.
  virtual void stop() = 0;

  // Recover the actual clip filename written by the device (via the device's own listing, §1.7).
  virtual std::string read_back_filename() = 0;

  // Report the device's current state token (the concrete state set is the adapter's concern).
  virtual std::string get_state() = 0;

  // Apply a capture profile descriptor (3K/100, FlowState off, audio-on — §4.2; held by the device).
  virtual void set_profile(const std::string& profile) = 0;

  // Write the sidecar record onto the device's capture medium.
  virtual void write_sidecar(const eunomia::Sidecar& record) = 0;
};

}  // namespace eunomia

#endif  // EUNOMIA_CAPTURE_DEVICE_PORT_H
