// GENERATED by contracts/codegen/generate.py from telemetry_event.schema.yaml - DO NOT EDIT.
#ifndef EUNOMIA_TELEMETRY_EVENT_H
#define EUNOMIA_TELEMETRY_EVENT_H

#include <string>

#include "eunomia_detail.h"

// Firmware-facing C++ target (OQ-5): a flat field-BAG view of the record. The struct flattens every
// scalar/string leaf (nested groups are flattened by their unique leaf key); parse/serialize look
// leaves up by key in the whole JSON (NO structural descent, via eunomia_detail.h). HARD leaves are
// required by parse(); WARN leaves are best-effort. Arrays / opaque objects / bool are not modeled.

namespace eunomia {

struct TelemetryEvent {
  std::string schema{};
  std::string event{};
  std::string kit_id{};
  long long ms{};
  std::string emitted_at{};
  std::string fob_session_id{};
  std::string episode_id{};
  long long episode_ordinal{};
  std::string side{};
  std::string station{};
  std::string prompt{};
  long long sent{};
  long long total{};
};

inline bool parse_telemetry_event(const std::string& s, TelemetryEvent& out) {
  if (!parse_string(s, "schema", out.schema)) return false;
  if (!parse_string(s, "event", out.event)) return false;
  if (!parse_string(s, "kit_id", out.kit_id)) return false;
  if (!parse_number(s, "ms", out.ms)) return false;
  if (!parse_string(s, "emitted_at", out.emitted_at)) return false;
  parse_string(s, "fob_session_id", out.fob_session_id);
  parse_string(s, "episode_id", out.episode_id);
  parse_number(s, "episode_ordinal", out.episode_ordinal);
  parse_string(s, "side", out.side);
  parse_string(s, "station", out.station);
  parse_string(s, "prompt", out.prompt);
  parse_number(s, "sent", out.sent);
  parse_number(s, "total", out.total);
  return true;
}

inline std::string serialize_telemetry_event(const TelemetryEvent& v) {
  std::string o = "{";
  o += "\"schema\":\"" + v.schema + "\"";
  o += ",\"event\":\"" + v.event + "\"";
  o += ",\"kit_id\":\"" + v.kit_id + "\"";
  o += ",\"ms\":" + std::to_string(v.ms);
  o += ",\"emitted_at\":\"" + v.emitted_at + "\"";
  o += ",\"fob_session_id\":\"" + v.fob_session_id + "\"";
  o += ",\"episode_id\":\"" + v.episode_id + "\"";
  o += ",\"episode_ordinal\":" + std::to_string(v.episode_ordinal);
  o += ",\"side\":\"" + v.side + "\"";
  o += ",\"station\":\"" + v.station + "\"";
  o += ",\"prompt\":\"" + v.prompt + "\"";
  o += ",\"sent\":" + std::to_string(v.sent);
  o += ",\"total\":" + std::to_string(v.total);
  o += "}";
  return o;
}

}  // namespace eunomia

#endif  // EUNOMIA_TELEMETRY_EVENT_H
