#!/usr/bin/env python3
"""Eunomia contract codegen (Run 0a proof): ONE neutral YAML schema -> THREE targets
(C++ header, Python dataclass + pure-stdlib validator, JSON Schema). Fixed scaffolding
lives in templates/; this fills the per-field slots. Deterministic output (sorted keys,
no timestamps) so the codegen-drift gate is meaningful.

Obvious by design and kept small. If it ever needs real complexity (nested types, the
interface ports, conditional validation), STOP and flag rather than growing it — the
approved OQ-10 rule; see README.md.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml  # type: ignore

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
SOURCE = ROOT / "contracts" / "_proof" / "ping.schema.yaml"
GEN = ROOT / "contracts" / "_generated"
MSG = f"GENERATED by contracts/codegen/generate.py from {SOURCE.name} - DO NOT EDIT."

# neutral type -> (python, cpp, json-schema)
TYPES = {
    "int": ("int", "long long", "integer"),
    "number": ("float", "double", "number"),
    "string": ("str", "std::string", "string"),
    "bool": ("bool", "bool", "boolean"),
}


def fill(template: str, **slots: str) -> str:
    for key, value in slots.items():
        template = template.replace(f"@{key}@", value)
    return template


def emit_jsonschema(spec: dict) -> str:
    doc = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": MSG,
        "title": spec["title"],
        "description": spec.get("description", ""),
        "type": "object",
        "properties": {
            f["name"]: {
                "type": TYPES[f["type"]][2],
                "description": f.get("description", ""),
            }
            for f in spec["fields"]
        },
        "required": [f["name"] for f in spec["fields"] if f.get("required") == "hard"],
        # additive semver: new fields are added, never renamed; old files still validate.
        "additionalProperties": True,
    }
    return json.dumps(doc, indent=2, sort_keys=True) + "\n"


def emit_python(spec: dict) -> str:
    fields = "\n".join(
        f"    {f['name']}: {TYPES[f['type']][0]}" for f in spec["fields"]
    )
    hard = "\n".join(
        f'    "{f["name"]}": "{f["type"]}",'
        for f in spec["fields"]
        if f.get("required") == "hard"
    )
    return fill(
        (HERE / "templates" / "module.py.tmpl").read_text(),
        MSG=MSG,
        TITLE=spec["title"],
        DESC=spec.get("description", ""),
        FIELDS=fields,
        HARD=hard,
    )


def emit_python_init(spec: dict) -> str:
    t = spec["title"]
    return (
        f'"""{MSG}"""\n\n'
        f"from eunomia_contracts.ping import {t}, validate, validate_full\n\n"
        f'__all__ = ["{t}", "validate", "validate_full"]\n'
    )


def emit_cpp(spec: dict) -> str:
    members = "\n".join(
        f"  {TYPES[f['type']][1]} {f['name']}{{}};" for f in spec["fields"]
    )
    parse = "\n".join(
        f'  if (!parse_number(s, "{f["name"]}", out.{f["name"]})) return false;'
        for f in spec["fields"]
        if f["type"] in ("int", "number")
    )
    ser = []
    for i, f in enumerate(spec["fields"]):
        sep = "" if i == 0 else ","
        ser.append(f'  o += "{sep}\\"{f["name"]}\\":" + std::to_string(v.{f["name"]});')
    return fill(
        (HERE / "templates" / "header.h.tmpl").read_text(),
        MSG=MSG,
        GUARD=f"EUNOMIA_{spec['title'].upper()}_H",
        TITLE=spec["title"],
        LOW=spec["title"].lower(),
        MEMBERS=members,
        PARSE=parse,
        SER="\n".join(ser),
    )


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  wrote {path.relative_to(ROOT)}")


def main() -> None:
    spec = yaml.safe_load(SOURCE.read_text())
    print(f"codegen: {SOURCE.relative_to(ROOT)} -> 3 targets")
    write(GEN / "jsonschema" / "ping.schema.json", emit_jsonschema(spec))
    write(GEN / "python" / "eunomia_contracts" / "ping.py", emit_python(spec))
    write(GEN / "python" / "eunomia_contracts" / "__init__.py", emit_python_init(spec))
    write(GEN / "cpp" / "eunomia_ping.h", emit_cpp(spec))


if __name__ == "__main__":
    main()
