#!/usr/bin/env python3
"""Eunomia INTERFACE codegen (Run 0c): the hardware-seam ports as operation SIGNATURES -> TWO targets
(a C++ pure-virtual abstract header + a Python ``typing.Protocol``). There is NO JSON Schema target —
an interface is not a data record.

This is a SEPARATE mini-emitter from the record generator ``generate.py`` (LEAD-OQ-A → option C):
signatures do not fit the record field-DSL, so folding them into ``generate.py`` would grow the record
generator into a second type system (the STOP-and-flag line). Keeping them in their own bounded emitter
is the opposite of framework-creep — ``generate.py`` stays records-only.

WIRING (OQ-8): this runs as a SIBLING command in ``make codegen`` (``generate.py`` then this), NOT
imported by ``generate.py`` — an intra-``codegen`` import breaks ``mypy .``-from-root under the
no-config gate (the OQ-8 lesson from 0b). Both write into ``contracts/_generated``, so the single
``git diff --exit-code contracts/_generated`` drift gate covers both: one source -> two targets, so the
C++ header and the Python Protocol cannot drift.

CLOSED TYPE VOCABULARY (the held boundary): an operation type MUST be one of ``_VOCAB``. The emitter
maps this FIXED set to each language; it is NOT a parser for an open type grammar. A type outside the
set raises SystemExit — a STOP-and-flag — rather than being silently handled (that is what keeps
option C from degrading into option A here).
"""

from __future__ import annotations

from pathlib import Path

import yaml  # type: ignore

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
GEN = ROOT / "contracts" / "_generated"
TEMPLATES = HERE / "templates"
SOURCE = ROOT / "contracts" / "interfaces" / "ports.iface.yaml"

_MSG = (
    "GENERATED by contracts/codegen/generate_interfaces.py from interfaces/ports.iface.yaml - "
    "DO NOT EDIT (edit the source + run `make codegen`)."
)

# The CLOSED vocabulary (LEAD-OQ-A boundary). Each semantic type maps to a concrete language type;
# several share a representation (std::string / str) — that is fine, they stay distinct in the IDL for
# readability + future strengthening. ``void`` is return-only; ``record`` is param-only.
_VOCAB = {
    "uuid",
    "str",
    "filename",
    "ack",
    "camera",
    "set[camera]",
    "record",
    "state",
    "profile",
    "void",
}
_CPP_RET = {
    "uuid": "std::string",
    "str": "std::string",
    "filename": "std::string",
    "camera": "std::string",
    "state": "std::string",
    "profile": "std::string",
    "ack": "bool",
    "set[camera]": "std::vector<std::string>",
    "void": "void",
}
_CPP_PARAM = {
    "uuid": "const std::string&",
    "str": "const std::string&",
    "filename": "const std::string&",
    "camera": "const std::string&",
    "state": "const std::string&",
    "profile": "const std::string&",
    "ack": "bool",
    "set[camera]": "const std::vector<std::string>&",
    "record": "const eunomia::Sidecar&",
}
_PY_TYPE = {
    "uuid": "str",
    "str": "str",
    "filename": "str",
    "camera": "str",
    "state": "str",
    "profile": "str",
    "ack": "bool",
    "set[camera]": "set[str]",
    "record": "Sidecar",
    "void": "None",
}


def _stop(msg: str) -> None:
    raise SystemExit(f"interface codegen STOP-and-flag: {msg}")


def _check_type(t: str, where: str) -> None:
    if t not in _VOCAB:
        _stop(
            f"type '{t}' ({where}) is not in the closed vocabulary {sorted(_VOCAB)} — "
            f"raise an OQ, do NOT extend the IDL."
        )


def _check_return(t: str, where: str) -> None:
    """A return type: in the closed vocabulary, and not the param-only ``record``."""
    _check_type(t, where)
    if t == "record":
        _stop(f"{where}: 'record' is param-only, not a return type")


def _check_param(t: str, where: str) -> None:
    """A param type: in the closed vocabulary, and not the return-only ``void``."""
    _check_type(t, where)
    if t == "void":
        _stop(f"{where}: 'void' is not a valid param type")


def fill(template: str, **slots: str) -> str:
    for key, value in slots.items():
        template = template.replace(f"@{key}@", value)
    return template


def snake(name: str) -> str:
    """CoordinatorPort -> coordinator_port."""
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def oneline(text: str) -> str:
    """Collapse a (possibly folded) doc string to a single deterministic line."""
    return " ".join(text.split())


# ---- target: C++ abstract header (pure-virtual class) ----


def emit_cpp_port(port: dict, msg: str) -> str:
    name = port["name"]
    uses_vector = False
    uses_record = False
    methods: list[str] = []
    for op in port["operations"]:
        ret = op["returns"]
        _check_return(ret, f"{name}.{op['name']} return")
        if ret == "set[camera]":
            uses_vector = True
        params: list[str] = []
        for p in op.get("params") or []:
            pt = p["type"]
            _check_param(pt, f"{name}.{op['name']} param {p['name']}")
            if pt == "set[camera]":
                uses_vector = True
            if pt == "record":
                uses_record = True
            params.append(f"{_CPP_PARAM[pt]} {p['name']}")
        sig = f"{_CPP_RET[ret]} {op['name']}({', '.join(params)})"
        methods.append(f"  // {oneline(op['doc'])}\n  virtual {sig} = 0;")

    includes = ["#include <string>"]
    if uses_vector:
        includes.append("#include <vector>")
    inc = "\n".join(includes)
    if uses_record:
        inc += '\n\n#include "eunomia_sidecar.h"'

    return fill(
        (TEMPLATES / "port.h.tmpl").read_text(),
        MSG=msg,
        GUARD=f"EUNOMIA_{snake(name).upper()}_H",
        INCLUDES=inc,
        CLASSDOC=f"// {oneline(port['doc'])}",
        CLASS=name,
        METHODS="\n\n".join(methods),
    )


# ---- target: Python typing.Protocol ----


def emit_python(ports: list, msg: str) -> str:
    uses_record = any(
        p["type"] == "record"
        for port in ports
        for op in port["operations"]
        for p in op.get("params") or []
    )
    imports = ["from typing import Protocol"]
    if uses_record:
        imports.append("from eunomia_contracts.sidecar import Sidecar")

    blocks: list[str] = []
    for port in ports:
        name = port["name"]
        lines = [f"class {name}(Protocol):", f'    """{oneline(port["doc"])}"""', ""]
        for op in port["operations"]:
            ret = op["returns"]
            _check_return(ret, f"{name}.{op['name']} return")
            params = ["self"]
            for p in op.get("params") or []:
                pt = p["type"]
                _check_param(pt, f"{name}.{op['name']} param {p['name']}")
                params.append(f"{p['name']}: {_PY_TYPE[pt]}")
            lines.append(
                f"    def {op['name']}({', '.join(params)}) -> {_PY_TYPE[ret]}: ..."
            )
        blocks.append("\n".join(lines))

    return fill(
        (TEMPLATES / "protocol.py.tmpl").read_text(),
        MSG=msg,
        IMPORTS="\n".join(imports),
        PROTOCOLS="\n\n\n".join(blocks),
    )


# ---- driver ----


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  wrote {path.relative_to(ROOT)}")


def main() -> None:
    ports = yaml.safe_load(SOURCE.read_text())["ports"]
    print(
        f"codegen(interfaces): {len(ports)} port(s) -> C++ abstract header + Python Protocol"
    )
    for port in ports:
        write(
            GEN / "cpp" / f"eunomia_{snake(port['name'])}.h", emit_cpp_port(port, _MSG)
        )
    write(
        GEN / "python" / "eunomia_contracts" / "interfaces.py", emit_python(ports, _MSG)
    )


if __name__ == "__main__":
    main()
